export interface SearchItem {
    id: string;
    keywords: string[];
    matchedKeyword?: string;
    title: string;
    description: string;
    url: string;
    section?: string;
    pageName: string;
}

export const searchData: SearchItem[] = [
    //     {
    //     id: "products",
    //     title: "Products",
    //     description: "Explore our services based on functional expertise",
    //     keywords: [
    //         "Capabilities",
    //         "Products"
    //     ],
    //     url: "/capabilities",
    //     section: "Products",
    //     pageName: "BCN PEG Products",
    // },
    // Sectors
    {
        id: "industry",
        title: "Industry",
        description: "Explore our specialized offerings tailored to specific industries",
        keywords: ["Sectors", "Industries"],
        url: "/industries",
        section: "Industry",
        pageName: "BCN PEG Industry",
    },
    {
        id: "financial-services",
        title: "Financial Services",
        description: "Unlock value in Financial Services with cutting-edge insights, proprietary data, and access to BCN PEG specialists and tools. Leverage deep sector knowledge to drive your next deal.",
        keywords: [
            "Financial services",
            "Market intelligence",
            "Sector expertise",
            "Proprietary data",
            "Deal lifecycle",
            "FS staffing",
            "Product catalog",
            "Market modelling",
            "Survey analytics",
            "Workforce analytics",
            "Digital analytics",
            "Sector scans",
            "Target screening",
            "Customer sentiment",
            "Disruption assessment",
            "ESG assessment",
            "Case studies",
            "Banking",
            "Asset management",
            "Insurance",
            "Wealth management",
            "Americas",
            "EMEA"
        ],
        url: "/industries/financial-services",
        section: "Sectors",
        pageName: "Financial Services",
    },
    {
        id: "healthcare",
        title: "Healthcare",
        description: "Healthcare focused analyses and insights to turbocharge your next PEG case. Includes key sector insights, BCN-driven DDs/ODAs, case studies, and direct access to tools and PEG healthcare experts.",
        keywords: [
            "Healthcare",
            "BCN PEG",
            "Sector insights",
            "Due diligence",
            "ODAs",
            "Case studies",
            "Healthcare playbook",
            "Quick diagnostic",
            "Ops DD solution",
            "Self-service tools",
            "Gx curve",
            "Loss of exclusivity model",
            "Providers due diligence",
            "Suppliers due diligence",
            "Payers due diligence",
            "Provider quick diagnostic",
            "Operational due diligence toolkit",
            "Patient surveys",
            "Physician interviews",
            "Workforce analytics",
            "Sector scans",
            "Target screening",
            "Pharma clinical data",
            "Clarivate DRG",
            "AIOCD",
            "Citeline",
            "IQVIA",
            "Evaluate",
            "Medtech market intelligence",
            "GlobalData",
            "Fitch Solutions",
            "Hospitals and providers data",
            "Definitive Healthcare",
            "AHD",
            "AHA DataQuery",
            "PEG Brain",
            "MSCI Healthcare Diagnostic",
            "Frost and Sullivan",
            "KLAS Research",
            "IQVIA Analytics",
            "EvaluatePharma",
            "GlobalData Medical"
        ],
        url: "/industries/healthcare",
        section: "Sectors",
        pageName: "Healthcare",
    },
    {
        id: "consumer-products-retail",
        title: "Consumer Products / Retail",
        description: "Consumer Products & Retail offerings including playbook, quick and full assessments, Consumer Pulse dashboards, custom analyses, and expert-led modules on disruption, survey, workforce, digital, sentiment, target screening, and ESG diligence.",
        keywords: [
            "Consumer products",
            "Retail",
            "CP&R",
            "BCN PEG",
            "Playbook",
            "Quick assessment",
            "Growth trajectory",
            "Channel split",
            "Retailer split",
            "Brand presence",
            "Expansion potential",
            "Velocity distribution",
            "Pricing positioning",
            "Product catalog",
            "Full assessment",
            "SKU deep dive",
            "Detailed growth trends",
            "Assortment analysis",
            "Promotional strategy",
            "Price positioning",
            "Consumer pulse",
            "Tableau solution",
            "Instant insights",
            "Ready-to-use dashboards",
            "Interactive filtering",
            "Custom analysis",
            "Disruption assessment",
            "Survey analytics",
            "Workforce analytics",
            "Digital analytics",
            "Sentiment analytics",
            "Target screening",
            "ESG diligence",
            "Case studies"
        ],
        url: "/industries/consumer-products",
        section: "Sectors",
        pageName: "Consumer Products / Retail",
    },
    {
        id: "technology",
        title: "Technology",
        description: "End-to-end tech diligence uncovering risks, opportunities, and investment needs—spanning architecture, code, security, talent, and ESG—to drive clear, actionable value",
        keywords: [
            "Technology",
            "Tech diligence",
            "Technology due diligence",
            "BCN PEG",
            "Architecture",
            "Code",
            "Cybersecurity",
            "Security",
            "Talent",
            "ESG",
            "HG insights",
            "RAVE",
            "Developer trends",
            "Self-service tools",
            "Commercial due diligence",
            "CDD",
            "Product roadmap",
            "Org structure",
            "SDLC",
            "R&D spend",
            "Tech stack",
            "UI/UX",
            "Hosting",
            "Code inventory",
            "Third party integrations",
            "Sector profiling",
            "Competitive landscape",
            "Customer perception",
            "Digital assessment",
            "Primary research",
            "Crunchbase",
            "Pitchbook",
            "S&P Global",
            "Gartner",
            "G2",
            "Forrester",
            "LinkedIn",
            "AURA",
            "Glassdoor",
            "Case studies",
            "Technology DD",
            "TDD workforce",
            "Feature benchmarking"
        ],
        url: "/industries/technology",
        section: "Sectors",
        pageName: "Technology",
    },

    // Capabilities
    {
        id: "products",
        title: "Products",
        description: "Explore our services based on functional expertise",
        keywords: [
            "Capabilities",
            "Products"
        ],
        url: "/capabilities",
        section: "Products",
        pageName: "BCN PEG Products",
    },
    {
        id: "survey-analytics",
        title: "Survey analytics",
        description: "Elevate your research with our end-to-end survey analytics solutions, offering everything from questionnaire design and panel coordination to advanced analytics and polished insights for both B2C and B2B surveys across industries",
        keywords: [
            "Survey analytics",
            "Questionnaire design",
            "Panel coordination",
            "Advanced analytics",
            "B2C surveys",
            "B2B surveys",
            "Industries",
            "Executive summary",
            "Product catalog",
            "Survey overview",
            "BDPs",
            "QC BDPs",
            "QC checks",
            "Valid respondents",
            "Bot detection",
            "AI Survey Builder",
            "NOVA",
            "Self-service tools",
            "Project scoping",
            "Vendor coordination",
            "Writing, coding and testing",
            "Soft launch",
            "Full launch",
            "Data modeling",
            "CFR model",
            "Excel model",
            "Tableau dashboard",
            "Case studies"
        ],
        url: "/capabilities/survey-analytics",
        section: "Products",
        pageName: "Survey analytics",
    },
    {
        id: "survey-designing",
        title: "Survey designing",
        description: "Developing survey questionnaire using case objectives/investment thesis and liaison with AIS for expert inputs",
        keywords: [
            "Survey designing",
            "Questionnaire development",
            "Case objectives",
            "Investment thesis",
            "AIS liaison",
            "AIS expert inputs"
        ],
        url: "/capabilities/survey-analytics/survey-designing",
        section: "Products",
        pageName: "Survey designing",
    },
    {
        id: "survey-coding-and-testing",
        title: "Survey coding and testing",
        description: "Test initial survey link / soft launch data to ensure accurate logic flows followed by course correction",
        keywords: [
            "Survey coding and testing",
            "Panel quota verification",
            "Survey link testing",
            "Soft launch execution",
            "Feedback analysis and adjustments",
            "Logic flows",
            "Representative sample",
            "Course correction",
            "Initial survey link",
            "Soft launch data"
        ],
        url: "/capabilities/survey-analytics/survey-coding",
        section: "Products",
        pageName: "Survey coding",
    },
    {
        id: "survey-analysis-and-insights",
        title: "Survey analysis and insights",
        description: "Automated cutter and self-serve platform (NOVA) to quickly analyze survey results complimented with slide output and insights",
        keywords: [
            "Survey analysis and insights",
            "Automated cutter",
            "Self-serve platform",
            "NOVA",
            "Survey analytics",
            "SaaS-based platform",
            "Instant analytics",
            "Advanced filtering",
            "Segmentation",
            "Data structuring",
            "Analytical cuts",
            "Investment thesis",
            "Dynamic Excel model",
            "Real-time integration",
            "Fraud detection",
            "CFR model",
            "Excel model",
            "Slide output",
            "Tableau dashboard",
            "Visualizations"
        ],
        url: "/capabilities/survey-analytics/survey-analysis",
        section: "Products",
        pageName: "Survey analysis",
    },
    {
        id: "survey-vendors",
        title: "Survey vendor directory",
        description: "Developing survey questionnaire using case objectives/investment thesis and liaison with AIS for expert inputs",
        keywords: [
            "Survey vendors",
            "Survey contacts",
            "Survey vendor PoCs",
            "IncQuery",
            "Dialectica",
            "Azure",
            "Bell & Holmes",
            "Jasper Colin",
            "Innovate MR",
            "Dynata",
            "ROI Rocket",
            "NIQ",
            "Kantar",
            "Ipsos",
            "Third Bridge",
            "AlphaSights",
            "GLG",
            "Explorare",
            "FFIND",
            "M3",
            "Sermo",
        ],
        url: "/capabilities/survey-analytics/survey-vendors",
        section: "Products",
        pageName: "Survey vendor directory",
    },
    {
        id: "workforce-analytics",
        title: "Workforce analytics",
        description: "Drive strategic decisions with comprehensive workforce analytics – track headcount trends, org structure, hiring and retention metrics. Elevate your talent strategy with powerful insights into employee sentiment, market pay trends, job postings, and productivity benchmarks",
        keywords: [
            "Workforce analytics",
            "Headcount trends",
            "Org structure",
            "Hiring metrics",
            "Retention metrics",
            "Talent strategy",
            "Employee sentiment",
            "Market pay trends",
            "Job postings",
            "Productivity benchmarks",
            "Self-service tools",
            "RAVE",
            "ClassifAI",
            "Organizational talent diagnostics",
            "FTE growth",
            "Tenure trends",
            "Attrition trends",
            "Functional distribution",
            "Geographic distribution",
            "Education background",
            "DE&I",
            "Glassdoor",
            "External market signals",
            "Compensation benchmarking",
            "Aura",
            "RDS"
        ],
        url: "/capabilities/workforce-analytics",
        section: "Products",
        pageName: "Workforce analytics",
    },
    {
        id: "digital-diagnostics",
        title: "Digital diagnostics",
        description: "Digital diagnostic helps discern digital performance and opportunities to optimize across growth levers, for all types of businesses while also providing drill-downs on specific digital levers – from an outside-in perspective",
        keywords: [
            "Digital diagnostics",
            "Digital performance",
            "Growth levers",
            "Outside-in perspective",
            "Digital marketing diagnostic",
            "SimilarWeb",
            "Semrush",
            "Pathmatics",
            "Mobile app performance",
            "Downloads",
            "MAUs",
            "Ratings",
            "SensorTower",
            "Web traffic",
            "Demographics",
            "Search engine performance",
            "Organic traffic",
            "Keywords",
            "Click-through rates",
            "CTR",
            "CPC",
            "Web-traffic and search marketing",
            "Social media",
            "Facebook",
            "Instagram",
            "X",
            "Twitter",
            "YouTube",
            "TikTok",
            "LinkedIn",
            "Influencer marketing",
            "E-commerce acceleration",
            "Amazon",
            "Sephora",
            "Consumer journey",
            "Marketing spend",
            "TV",
            "Print",
            "Radio",
            "OOH",
            "Mobile apps",
            "DAUs",
            "Session counts",
            "Retention",
            "User sentiment",
            "Consumer sentiment",
            "AI sentiment analysis",
            "Text-based reviews"
        ],
        url: "/capabilities/digital",
        section: "Products",
        pageName: "Digital diagnostics",
    },
    {
        id: "esg-carbon-assessment",
        title: "ESG / Carbon assessment",
        description: "ESG analysis helps gain insights into material ESG issues for the industry and benchmark company maturity and capabilities on key ESG issues from an outside-in perspective",
        keywords: [
            "ESG analysis",
            "Carbon assessment",
            "Material ESG issues",
            "Outside-in perspective",
            "ESG diagnostic",
            "Due diligence approach",
            "Material themes",
            "Materiality",
            "ESG benchmarks",
            "Value creation levers",
            "ESG One Day Assessment",
            "ODA",
            "ESG Due Diligence",
            "Regulatory landscape",
            "Controversies scan",
            "GHG emissions",
            "Decarbonization assessment",
            "ESG target screening",
            "Customer sentiment",
            "Automated diagnostic",
            "Self-service tools",
            "ESG Beacon",
            "Climate risk assessment",
            "Flood risk",
            "Fire risk",
            "Wind risk",
            "PEG Brain",
            "ESG Ringfence team"
        ],
        url: "/capabilities/esg",
        section: "Products",
        pageName: "ESG / Carbon assessment",
    },
    {
        id: "sector-scan-target-screening",
        title: "Sector scan / Target screening",
        description: "Identify high-potential acquisition targets with tailored scans and deep-dive profiles, powered by proprietary tools and AI-driven insights",
        keywords: [
            "Sector scan",
            "Target screening",
            "Acquisition targets",
            "Tailored scans",
            "Deep-dive profiles",
            "Proprietary tools",
            "AI-driven insights",
            "BCN PEG",
            "Sector scan solutions",
            "Target screening solutions",
            "Product catalog",
            "Expert access"
        ],
        url: "/capabilities/sector-scan",
        section: "Products",
        pageName: "Sector scan / Target screening",
    },
    {
        id: "gen-ai",
        title: "Gen AI",
        description: "End-to-end GenAI Due Diligence (DD) from scoping to delivery, using GenAI tools and expert insights to assess impact, identify disruptions, generate outputs, and prototype AI applications",
        keywords: [
            "Gen AI",
            "GenAI due diligence",
            "DD",
            "Scoping",
            "Delivery",
            "GenAI tools",
            "Expert insights",
            "Assess impact",
            "Identify disruptions",
            "Generate outputs",
            "Prototype AI applications",
            "GenAI Executive Summary",
            "BCN PEG product catalog",
            "AI-powered research",
            "Data synthesis tools",
            "Tailored approaches",
            "Expert calls",
            "Customer calls",
            "Competitor calls"
        ],
        url: "/capabilities/gen-ai",
        section: "Products",
        pageName: "Gen AI"
    },

    // PEG Tools
    {
        id: "nova",
        title: "NOVA",
        description: "Unlock instant insights with our SaaS-based survey platform with one click, using advanced filtering and segmentation",
        keywords: [
            "NOVA",
            "Survey analytics",
            "SaaS survey platform",
            "Instant insights",
            "Advanced filtering",
            "Segmentation",
            "Survey data analysis",
            "One-click analytics"
        ],
        url: "/peg-tools#bcn-peg-tools",
        section: "PEG Tools",
        pageName: "PEG Tools"
    },
    {
        id: "expert-network-outreach-tool",
        title: "Expert network outreach tool",
        description: "Expert guidance for complex business challenges. Launch expert outreach across multiple networks using a single form—simple, fast, centralized",
        keywords: [
            "Expert network outreach tool",
            "Expert guidance",
            "Complex business challenges",
            "Expert outreach",
            "Multiple networks",
            "Centralized outreach",
            "Single form"
        ],
        url: "/peg-tools#other-peg-tools",
        section: "PEG Tools",
        pageName: "PEG Tools"
    },
    {
        id: "pexc",
        title: "PEXC",
        description: "Fast, secure access to Bain’s diligence insights. Search Bain’s diligence archive and request secure, read-only access to past case materials",
        keywords: [
            "PEXC",
            "Fast access",
            "Secure access",
            "Diligence insights",
            "Diligence archive",
            "Read-only access",
            "Past case materials"
        ],
        url: "/peg-tools#other-peg-tools",
        section: "PEG Tools",
        pageName: "PEG Tools"
    },
    {
        id: "peg-brain",
        title: "PEG Brain",
        description: "Centralized repository for Bain tools and databases. A web-based platform designed to help identify the right tools for various use cases during the diligence process",
        keywords: [
            "PEG Brain",
            "Repository",
            "Bain tools",
            "Databases",
            "Web-based platform",
            "Diligence process"
        ],
        url: "/peg-tools#other-peg-tools",
        section: "PEG Tools",
        pageName: "PEG Tools"
    },
    {
        id: "glassdoor",
        title: "Glassdoor",
        description: "Pull Glassdoor reviews and ratings. Extract employee reviews and ratings from Glassdoor via RAVE for cultural benchmarking",
        keywords: [
            "Glassdoor",
            "Employee reviews",
            "Ratings",
            "RAVE",
            "Cultural benchmarking"
        ],
        url: "/peg-tools#employee-reviews",
        section: "PEG Tools",
        pageName: "PEG Tools"
    },
    {
        id: "indeed",
        title: "Indeed",
        description: "Capture employee reviews from Indeed. Extract employee-generated reviews from Indeed to assess culture and workplace sentiment",
        keywords: [
            "Indeed",
            "Employee reviews",
            "Workplace sentiment",
            "Culture",
            "Employee-generated reviews"
        ],
        url: "/peg-tools#employee-reviews",
        section: "PEG Tools",
        pageName: "PEG Tools"
    },
    {
        id: "pe-pulse-tool",
        title: "PE Pulse tool",
        description: "Instant fund intelligence. Search Bain’s growing repository of Mid-Market PE fund manager intelligence, and quickly navigate through key profile metrics, fund performance, and download detailed Redbook",
        keywords: [
            "PE pulse tool",
            "Fund intelligence",
            "Mid-market PE",
            "Profile metrics",
            "Fund performance",
            "Redbook"
        ],
        url: "/peg-tools#bcn-peg-tools",
        section: "PEG Tools",
        pageName: "PEG Tools"
    },
    {
        id: "pe-pulse-live",
        title: "PE Pulse live",
        description: "Instant fund intelligence – Tableau dashboard. Live PE Pulse Tableau dashboard for on-demand comparison of fund performance across vintages",
        keywords: [
            "PE pulse live",
            "Fund intelligence",
            "Tableau dashboard",
            "Fund performance",
            "Vintages"
        ],
        url: "/peg-tools#bcn-peg-tools",
        section: "PEG Tools",
        pageName: "PEG Tools"
    },
    {
        id: "geo-coding",
        title: "Geo coding",
        description: "Convert between addresses and coordinates with ease. Convert addresses to lat/long/place ID or reverse geocode coordinates into readable locations",
        keywords: [
            "Geo coding",
            "Addresses",
            "Coordinates",
            "Lat/long",
            "Place ID",
            "Reverse geocode",
            "Readable locations"
        ],
        url: "/peg-tools#geo-scrapers",
        section: "PEG Tools",
        pageName: "PEG Tools"
    },
    {
        id: "geo-distance",
        title: "Geo distance",
        description: "Calculate straight-line / driving distance. Measure straight-line or driving distances between locations to support routing or logistics",
        keywords: [
            "Geo distance",
            "Straight-line distance",
            "Driving distance",
            "Routing",
            "Logistics"
        ],
        url: "/peg-tools#geo-scrapers",
        section: "PEG Tools",
        pageName: "PEG Tools"
    },
    {
        id: "geo-plotting",
        title: "Geo plotting",
        description: "Plot locations on a map or as GeoJSON. Visualize location data on an interactive map or export to GeoJSON for further analysis",
        keywords: [
            "Geo plotting",
            "Map",
            "GeoJSON",
            "Visualization",
            "Interactive map",
            "Location data"
        ],
        url: "/peg-tools#geo-scrapers",
        section: "PEG Tools",
        pageName: "PEG Tools"
    },
    {
        id: "gartner",
        title: "Gartner",
        description: "Extract software product reviews from Gartner. Collect software reviews from Gartner for sentiment insights and competitor comparisons",
        keywords: [
            "Gartner",
            "Software product reviews",
            "Sentiment insights",
            "Competitor comparisons"
        ],
        url: "/peg-tools#company-reviews",
        section: "PEG Tools",
        pageName: "PEG Tools"
    },
    {
        id: "amazon-product-details",
        title: "Amazon (Product details)",
        description: "Collect product details from Amazon listings. Extract detailed product data from Amazon pages for tracking, comparison, or analysis",
        keywords: [
            "Amazon product details",
            "Product details",
            "Amazon listings",
            "Product data",
            "Tracking",
            "Comparison",
            "Analysis"
        ],
        url: "/peg-tools#product-reviews",
        section: "PEG Tools",
        pageName: "PEG Tools"
    },
    {
        id: "amazon-product-search",
        title: "Amazon",
        description: "Automated product searches on Amazon. Search Amazon by keyword and extract key product details from search result listings",
        keywords: [
            "Amazon product search",
            "Product search",
            "Keyword search",
            "Product details"
        ],
        url: "/peg-tools#product-search",
        section: "PEG Tools",
        pageName: "PEG Tools"
    },
    {
        id: "best-buy-product-reviews",
        title: "Best Buy",
        description: "Extract product reviews from Best Buy. Scrape Best Buy product reviews to support sentiment analysis and competitive insights",
        keywords: [
            "Best Buy product reviews",
            "Sentiment analysis",
            "Competitive insights",
            "Best Buy"
        ],
        url: "/peg-tools#product-reviews",
        section: "PEG Tools",
        pageName: "PEG Tools"
    },
    {
        id: "best-buy-product-search",
        title: "Best Buy",
        description: "Automate product searches on Best Buy. Automate keyword-based product searches on Best Buy and extract structured details",
        keywords: [
            "Best Buy product search",
            "Keyword-based search",
            "Structured details",
            "Best Buy"
        ],
        url: "/peg-tools#product-search",
        section: "PEG Tools",
        pageName: "PEG Tools"
    },
    {
        id: "target-product-reviews",
        title: "Target",
        description: "Extract product reviews from Target. Scrape product reviews from Target to gain insight into customer sentiment and feedback",
        keywords: [
            "Target product reviews",
            "Customer sentiment",
            "Feedback",
            "Target"
        ],
        url: "/peg-tools#product-reviews",
        section: "PEG Tools",
        pageName: "PEG Tools"
    },
    {
        id: "target-product-search",
        title: "Target",
        description: "Automated product searches on Target. Use front-end site search to extract structured product data from Target search results",
        keywords: [
            "Target product search",
            "Structured product data",
            "Site search",
            "Target"
        ],
        url: "/peg-tools#product-search",
        section: "PEG Tools",
        pageName: "PEG Tools"
    },
    {
        id: "trustpilot",
        title: "Trustpilot",
        description: "Scrape company reviews from Trustpilot. Collect Trustpilot reviews to understand brand sentiment and customer experience trends",
        keywords: [
            "Trustpilot",
            "Company reviews",
            "Brand sentiment",
            "Customer experience"
        ],
        url: "/peg-tools#company-reviews",
        section: "PEG Tools",
        pageName: "PEG Tools"
    },
    {
        id: "yelp",
        title: "Yelp",
        description: "Extract localized reviews and business data from Yelp. Scrape reviews and local business data from Yelp profiles to analyze customer feedback",
        keywords: [
            "Yelp",
            "Localized reviews",
            "Business data",
            "Customer feedback"
        ],
        url: "/peg-tools#company-reviews",
        section: "PEG Tools",
        pageName: "PEG Tools"
    },
    {
        id: "hg-insights",
        title: "HG Insights",
        description: "Customer mix analysis using HG Insights. Segment customer data by size, geography, and industry to create client-ready outputs",
        keywords: [
            "HG Insights",
            "Customer mix analysis",
            "Segment customer data",
            "Size",
            "Industry",
            "Client-ready outputs"
        ],
        url: "/peg-tools#customer-analysis",
        section: "PEG Tools",
        pageName: "PEG Tools"
    },
    {
        id: "google-reviews",
        title: "Google",
        description: "Extract reviews from Google business profiles. Scrape location-specific Google reviews for sentiment analysis and local benchmarking",
        keywords: [
            "Google reviews",
            "Business profiles",
            "Sentiment analysis",
            "Local benchmarking"
        ],
        url: "/peg-tools#company-reviews",
        section: "PEG Tools",
        pageName: "PEG Tools"
    }
]
